# Pandas

* Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures.

* Using Pandas, we can accomplish five typical steps in the processing and analysis of data, regardless of the origin of data — load, prepare, manipulate, model, and analyze.



* Pandas deals with the following three data structures

    1) Series

    2) DataFrame

    3) Panel - [The Panel class is deprecated and has been removed in recent versions of pandas. The recommended way to represent 3-D data is with a MultiIndex on a DataFrame]

## 1) Series
Series is a one-dimensional array like structure with homogeneous data.
    
### Creating Series
A series can be created using various inputs like −

1) Array.

2) Dict.

3) Scalar value or constant

##### installing pandas

In [68]:
# !pip install pandas

#### 1) Array

In [69]:
#import the pandas library and aliasing as pd
import pandas as pd
import numpy as np

In [70]:
#Without passing index
#numpy array
arr = np.array(['a','b','c','d'])
print(arr)

['a' 'b' 'c' 'd']

In [71]:
#creating the series using numpy array
s = pd.Series(arr)
print(s)

0    a
1    b
2    c
3    d
dtype: str

In [72]:
#check the type
type(s)

pandas.Series

In [73]:
#by passing index.
#numpy array
arr = np.array(['a','b','c','d'])

#creating series
s = pd.Series(arr,index=[100,101,102,103])
s

100    a
101    b
102    c
103    d
dtype: str

#### 2) Dictionary
here keys will be our default indexes

In [74]:
# Ex1)
data = {'a' : 0, 'b' : 1, 'c' : 2}
s = pd.Series(data)
s

a    0
b    1
c    2
dtype: int64

#### Scalar

In [75]:
# Create a Series from Scalar
s = pd.Series(5, index=[0, 1, 2, 3])
s

0    5
1    5
2    5
3    5
dtype: int64

### Accessing Data from Series

#### 1) By using the position

In [76]:
# Data in the series can be accessed similar to that in an ndarray.
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [77]:
#retrieve the first element
s[0]

np.int64(1)

In [78]:
# first 3 elements
s[0:3]   #[start,stop,step] # remember stop is exclusive

0    1
1    2
2    3
dtype: int64

In [79]:
# last 3 elements
s[-3:]

2    3
3    4
4    5
dtype: int64

#### 2) By using the keys

In [80]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [81]:
#retrieve a single element
s['a']

np.int64(1)

In [82]:
#retrieve a multiple elements
s[['a','b','c']]

a    1
b    2
c    3
dtype: int64

#### to get the indexes

In [83]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

#### to get the values

In [84]:
s.values

array([1, 2, 3, 4, 5])

## DataFrame
A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns

### Create an Empty DataFrame

In [85]:
# A basic DataFrame, which can be created is an Empty Dataframe.
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

### Create a DataFrame from Dict of lists/ndArray
* All the ndarrays must be of same length.
* If index is passed, then the length of the index should equal to the length of the arrays.
* If no index is passed, then by default, index will be range(n), where n is the array length.

In [86]:
# Ex1) without index
name = ['Ashay', 'Himanshu', 'Padam', 'Ravi']
age = [22,23,24,25]

# creating dictionary
data = {'Name':name,'Age':age}
print(data)
# passing dictionary to create df
df = pd.DataFrame(data)
df

{'Name': ['Ashay', 'Himanshu', 'Padam', 'Ravi'], 'Age': [22, 23, 24, 25]}

       Name  Age
0     Ashay   22
1  Himanshu   23
2     Padam   24
3      Ravi   25

In [87]:
#Ex2) with index
name = ['Ashay', 'Himanshu', 'Padam', 'Ravi']
age = [22,23,24,25]

# my new indexes
indexes = ['rank1','rank2','rank3','rank4']

#this is my dictionary
data = {'Name':name,'Age':age}

#passing dictionary to create dataframe
df = pd.DataFrame(data, index=indexes)
df

           Name  Age
rank1     Ashay   22
rank2  Himanshu   23
rank3     Padam   24
rank4      Ravi   25

### Column Selection

In [88]:
df['Age']

rank1    22
rank2    23
rank3    24
rank4    25
Name: Age, dtype: int64

In [89]:
df.Age

rank1    22
rank2    23
rank3    24
rank4    25
Name: Age, dtype: int64

### Column Addition

In [90]:
# say suppose you want to add city column
city = ['Banglore','Pune','Hyderabad','Mumbai']

#adding new column named 'City'
df["City"] = city
df

           Name  Age       City
rank1     Ashay   22   Banglore
rank2  Himanshu   23       Pune
rank3     Padam   24  Hyderabad
rank4      Ravi   25     Mumbai

### Column Deletion

In [91]:
# 1) Using del keyword
del df["City"]
df

           Name  Age
rank1     Ashay   22
rank2  Himanshu   23
rank3     Padam   24
rank4      Ravi   25

In [92]:
# 2) Using pop function
df.pop('Age')
df

           Name
rank1     Ashay
rank2  Himanshu
rank3     Padam
rank4      Ravi

## built-in important functions

In [93]:
random = np.random.randint(low = 0, high =100, size = 20)
name = np.random.choice(['A', 'B', 'C', 'D', 'E'],size =  20)
choice = np.random.choice([10,11,13,12,14],size = 20)

#creating dictionary
dict1 = {
    'Random':random, 
    'Name':name,
    'Choice':choice
}

#creating dataframe
df = pd.DataFrame(dict1)
df

    Random Name  Choice
0       44    C      13
1        6    B      14
2       99    A      13
3       65    A      14
4       60    E      10
5       64    C      14
6       42    A      10
7       29    B      14
8       60    A      10
9       25    E      14
10      58    C      13
11      81    E      13
12      37    E      10
13      55    D      13
14      50    A      14
15      95    C      12
16      27    E      14
17      78    D      10
18       0    E      14
19      37    E      14

In [94]:
df.head()

   Random Name  Choice
0      44    C      13
1       6    B      14
2      99    A      13
3      65    A      14
4      60    E      10

In [95]:
df.tail()

    Random Name  Choice
15      95    C      12
16      27    E      14
17      78    D      10
18       0    E      14
19      37    E      14

In [96]:
df.head(2)

   Random Name  Choice
0      44    C      13
1       6    B      14

In [97]:
df.tail(4)

    Random Name  Choice
16      27    E      14
17      78    D      10
18       0    E      14
19      37    E      14

In [98]:
df.describe()

         Random     Choice
count  20.00000  20.000000
mean   50.60000  12.650000
std    26.50005   1.663066
min     0.00000  10.000000
25%    35.00000  11.500000
50%    52.50000  13.000000
75%    64.25000  14.000000
max    99.00000  14.000000

In [99]:
# similarly you can check for individual columns
df['Random'].describe()

count    20.00000
mean     50.60000
std      26.50005
min       0.00000
25%      35.00000
50%      52.50000
75%      64.25000
max      99.00000
Name: Random, dtype: float64

In [100]:
''' 
using inplace = True, it just mdified the dataframe in background
without inplace = True, it returns the mdified the dataframe
 '''
df.set_index('Random',inplace = True)

In [101]:
df

       Name  Choice
Random
44        C      13
6         B      14
99        A      13
65        A      14
60        E      10
64        C      14
42        A      10
29        B      14
60        A      10
25        E      14
58        C      13
81        E      13
37        E      10
55        D      13
50        A      14
95        C      12
27        E      14
78        D      10
0         E      14
37        E      14

In [102]:
df.sort_index(ascending=True) ## sort by index column

       Name  Choice
Random
0         E      14
6         B      14
25        E      14
27        E      14
29        B      14
37        E      14
37        E      10
42        A      10
44        C      13
50        A      14
55        D      13
58        C      13
60        E      10
60        A      10
64        C      14
65        A      14
78        D      10
81        E      13
95        C      12
99        A      13

In [103]:
df

       Name  Choice
Random
44        C      13
6         B      14
99        A      13
65        A      14
60        E      10
64        C      14
42        A      10
29        B      14
60        A      10
25        E      14
58        C      13
81        E      13
37        E      10
55        D      13
50        A      14
95        C      12
27        E      14
78        D      10
0         E      14
37        E      14

In [104]:
# to access the 11th element in name Column
df.iloc[11,0]

'E'

In [105]:
# to access the 5th element in Choice Column
df.iloc[4,1]

np.int64(10)

In [106]:
# similarly you can do the slicing here as well

# to get first 5 rows 
df.iloc[0:5]

       Name  Choice
Random
44        C      13
6         B      14
99        A      13
65        A      14
60        E      10

In [107]:
# to get first 10 rows and first 2 columns
df.iloc[:10,:2]  #start:stop:step

       Name  Choice
Random
44        C      13
6         B      14
99        A      13
65        A      14
60        E      10
64        C      14
42        A      10
29        B      14
60        A      10
25        E      14

In [108]:
dict1 = {
    "city" : ["A","B","C","D","E"],
    "temperature" : [32,33,34,35,36]
}

df1 = pd.DataFrame(dict1)
print(df1)
dict2 = {
    "city" : ["C","D","E","F","G"],
    "humidity" : [65,66,67,68,69]
}

df2 = pd.DataFrame(dict2)
print(df2)

  city  temperature
0    A           32
1    B           33
2    C           34
3    D           35
4    E           36
  city  humidity
0    C        65
1    D        66
2    E        67
3    F        68
4    G        69

In [109]:
pd.concat([df1,df2], axis =0)

  city  temperature  humidity
0    A         32.0       NaN
1    B         33.0       NaN
2    C         34.0       NaN
3    D         35.0       NaN
4    E         36.0       NaN
0    C          NaN      65.0
1    D          NaN      66.0
2    E          NaN      67.0
3    F          NaN      68.0
4    G          NaN      69.0

In [110]:
pd.concat([df1,df2], axis = 0, ignore_index=True) # creates new index

  city  temperature  humidity
0    A         32.0       NaN
1    B         33.0       NaN
2    C         34.0       NaN
3    D         35.0       NaN
4    E         36.0       NaN
5    C          NaN      65.0
6    D          NaN      66.0
7    E          NaN      67.0
8    F          NaN      68.0
9    G          NaN      69.0

In [111]:
pd.concat([df1,df2], axis = 1)

  city  temperature city  humidity
0    A           32    C        65
1    B           33    D        66
2    C           34    E        67
3    D           35    F        68
4    E           36    G        69

In [112]:
df = pd.merge(df1,df2, on='city')
df
# observe by default it is performing inner join

  city  temperature  humidity
0    C           34        65
1    D           35        66
2    E           36        67

In [113]:
pd.merge(df1,df2, on='city', how ='outer')

  city  temperature  humidity
0    A         32.0       NaN
1    B         33.0       NaN
2    C         34.0      65.0
3    D         35.0      66.0
4    E         36.0      67.0
5    F          NaN      68.0
6    G          NaN      69.0

In [114]:
pd.merge(df1,df2, on='city', how ='left')

  city  temperature  humidity
0    A           32       NaN
1    B           33       NaN
2    C           34      65.0
3    D           35      66.0
4    E           36      67.0

In [115]:
pd.merge(df1,df2, on='city', how ='right')

  city  temperature  humidity
0    C         34.0        65
1    D         35.0        66
2    E         36.0        67
3    F          NaN        68
4    G          NaN        69

##  Data cleaning

In [116]:
# creating a dataframe
dict1 = {
    0:[1,4,7,np.nan],
    1:[2,5,np.nan,np.nan],
    2:[3,np.nan,np.nan,np.nan],
    3:[np.nan,np.nan,np.nan,np.nan]
}

df = pd.DataFrame(dict1)
df

     0    1    2   3
0  1.0  2.0  3.0 NaN
1  4.0  5.0  NaN NaN
2  7.0  NaN  NaN NaN
3  NaN  NaN  NaN NaN

In [117]:
#to detect missing values
df.isnull()

       0      1      2     3
0  False  False  False  True
1  False  False   True  True
2  False   True   True  True
3   True   True   True  True

In [118]:
# Detect existing (non-missing) values.
df.notnull()

       0      1      2      3
0   True   True   True  False
1   True   True  False  False
2   True  False  False  False
3  False  False  False  False

In [119]:
#drops an entire row if one nan value is present
df.dropna()

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [120]:
# deletes the rows in which all the values are null
df.dropna(how='all')

     0    1    2   3
0  1.0  2.0  3.0 NaN
1  4.0  5.0  NaN NaN
2  7.0  NaN  NaN NaN

In [121]:
# deletes the columns in which all the values are null
df.dropna(axis=1, how='all')

     0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  NaN
2  7.0  NaN  NaN
3  NaN  NaN  NaN

In [122]:
# threshold Require that many 'non-nan' values.
df.dropna(thresh=1)

     0    1    2   3
0  1.0  2.0  3.0 NaN
1  4.0  5.0  NaN NaN
2  7.0  NaN  NaN NaN

In [123]:
df.dropna(thresh=1,axis = 1)

     0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  NaN
2  7.0  NaN  NaN
3  NaN  NaN  NaN

In [124]:
df

     0    1    2   3
0  1.0  2.0  3.0 NaN
1  4.0  5.0  NaN NaN
2  7.0  NaN  NaN NaN
3  NaN  NaN  NaN NaN

In [125]:
# to fill perticular values in all NaN
df_fill = df.fillna(10)
df_fill

      0     1     2     3
0   1.0   2.0   3.0  10.0
1   4.0   5.0  10.0  10.0
2   7.0  10.0  10.0  10.0
3  10.0  10.0  10.0  10.0

In [126]:
# to fill perticular values in perticular columns
df_fill = df.fillna({0: 10, 1: 20, 2: 30, 3: 40})
df_fill

      0     1     2     3
0   1.0   2.0   3.0  40.0
1   4.0   5.0  30.0  40.0
2   7.0  20.0  30.0  40.0
3  10.0  20.0  30.0  40.0

In [127]:
# fills the nan value with previous observation/row value
df_fill = df.fillna(value='NA')
df_fill

     0    1    2   3
0  1.0  2.0  3.0  NA
1  4.0  5.0   NA  NA
2  7.0   NA   NA  NA
3   NA   NA   NA  NA

In [128]:
#if you specify the limit,then only for those many 'NaN' values in a column it will fill the values
df_fill = df.fillna(value ={0: 10, 1: 20, 2: 30, 3: 40}, limit = 2)
df_fill

      0     1     2     3
0   1.0   2.0   3.0  40.0
1   4.0   5.0  30.0  40.0
2   7.0  20.0  30.0   NaN
3  10.0  20.0   NaN   NaN

In [129]:
# fills the nan value with previous mean of column
df_mean = df.fillna(df.mean())
df_mean

     0    1    2   3
0  1.0  2.0  3.0 NaN
1  4.0  5.0  3.0 NaN
2  7.0  3.5  3.0 NaN
3  4.0  3.5  3.0 NaN

In [130]:
# fills the nan value with previous mean of row
df_mean = df.fillna(df.mean(), axis=1)
df_mean

     0    1    2    3
0  1.0  2.0  3.0  4.0
1  4.0  5.0  3.5  3.5
2  7.0  3.0  3.0  3.0
3  NaN  NaN  NaN  NaN

In [131]:
# fills the nan value with previous median of column
df_median = df.fillna(df.median())
df_median

     0    1    2   3
0  1.0  2.0  3.0 NaN
1  4.0  5.0  3.0 NaN
2  7.0  3.5  3.0 NaN
3  4.0  3.5  3.0 NaN