In [82]:
import pandas as pd

In [83]:
ds = pd.Series([2, 4, 6, 8, 10])
ds

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [84]:
ds = pd.Series([2, 4, 6, 8, 10])
print("Series to List:", ds.tolist())
print("Type:", type(ds.tolist()))

Series to List: [2, 4, 6, 8, 10]
Type: <class 'list'>

In [85]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
print("Add:\n", s1 + s2)
print("Subtract:\n", s1 - s2)
print("Multiply:\n", s1 * s2)
print("Divide:\n", s1 / s2)

Add:
 0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract:
 0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply:
 0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [86]:
import numpy as np

In [87]:
arr = np.arange(7)
powers = np.power(arr, 3) 
print("Original array:", arr)
print("Element-wise powers:", powers)

Original array: [0 1 2 3 4 5 6]
Element-wise powers: [  0   1   8  27  64 125 216]

In [88]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [89]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     str
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes

In [90]:
df.iloc[:3]

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [91]:
df[['name', 'score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [92]:
df.loc[['a','c','e','f'],['name','score']]

        name  score
a  Anastasia   12.5
c  Katherine   16.5
e      Emily    9.0
f    Michael   20.0

In [93]:
df[df['attempts'] > 2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [94]:
print("Rows:", len(df.index))
print("Columns:", len(df.columns))

Rows: 10
Columns: 4

In [95]:
df[df['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [96]:
df[(df['attempts'] < 2) & (df['score'] > 15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

In [97]:
df.loc['d', 'score'] = 11.5
df.loc['d']

name        James
score        11.5
attempts        3
qualify        no
Name: d, dtype: object

In [98]:
print("Total attempts:", df['attempts'].sum())

Total attempts: 19

In [99]:
df.groupby('name')['score'].mean()

name
Anastasia    12.5
Dima          9.0
Emily         9.0
James        11.5
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Name: score, dtype: float64

In [100]:
df.loc['k'] = ['Suresh', 15.5, 1, 'yes']
print("With row k:\n", df)

df = df.drop('k')
print("Original DataFrame restored:\n", df)

With row k:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes
Original DataFrame restored:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [101]:
df = df.sort_values(by=['name', 'score'], ascending=[False, True])
df

        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [102]:
df['qualify'] = df['qualify'].replace({'yes': True, 'no': False})
df

        name  score  attempts qualify
f    Michael   20.0         3    True
g    Matthew   14.5         1    True
h      Laura    NaN         1   False
i      Kevin    8.0         2   False
c  Katherine   16.5         2    True
j      Jonas   19.0         1    True
d      James   11.5         3   False
e      Emily    9.0         2   False
b       Dima    9.0         3   False
a  Anastasia   12.5         1    True

In [103]:
df.pop('attempts')
df

        name  score qualify
f    Michael   20.0    True
g    Matthew   14.5    True
h      Laura    NaN   False
i      Kevin    8.0   False
c  Katherine   16.5    True
j      Jonas   19.0    True
d      James   11.5   False
e      Emily    9.0   False
b       Dima    9.0   False
a  Anastasia   12.5    True

In [104]:
df['attempts'] = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
df

        name  score qualify  attempts
f    Michael   20.0    True         1
g    Matthew   14.5    True         3
h      Laura    NaN   False         2
i      Kevin    8.0   False         3
c  Katherine   16.5    True         2
j      Jonas   19.0    True         3
d      James   11.5   False         1
e      Emily    9.0   False         1
b       Dima    9.0   False         2
a  Anastasia   12.5    True         1

In [117]:
for index, row in df.iterrows():
    print(f"Index: {index} | Name: {row['name']} | Score: {row['score']} | attempts: {row['attempts']} | qualify: {row['qualify']}")

Index: f | Name: Michael | Score: 20.0 | attempts: 1 | qualify: True
Index: g | Name: Matthew | Score: 14.5 | attempts: 3 | qualify: True
Index: h | Name: Laura | Score: nan | attempts: 2 | qualify: False
Index: i | Name: Kevin | Score: 8.0 | attempts: 3 | qualify: False
Index: c | Name: Katherine | Score: 16.5 | attempts: 2 | qualify: True
Index: j | Name: Jonas | Score: 19.0 | attempts: 3 | qualify: True
Index: d | Name: James | Score: 11.5 | attempts: 1 | qualify: False
Index: e | Name: Emily | Score: 9.0 | attempts: 1 | qualify: False
Index: b | Name: Dima | Score: 9.0 | attempts: 2 | qualify: False
Index: a | Name: Anastasia | Score: 12.5 | attempts: 1 | qualify: True

In [106]:
list(df.columns)

['name', 'score', 'qualify', 'attempts']